### ISSUE TITLE
Error when editing Contacts page in demo

### ISSUE THREAD

**Issue by AngeloHulshout** [entando/app-builder#374]
Clicking edit on the Contacts page in the app-builder gives an exception.
This happens in a version build on from source on MacOS, using 5.0.1 SNAPSHOT.

×
TypeError: undefined is not an object (evaluating 'options.find(function (opt) {
            return opt[valueKey] === value;
          })[labelKey]')
(anonymous function)
src/ui/pages/common/MultiSelectRenderer.js:34
  31 | } = this.props;
  32 | return selectedValues.map((value, i) => (
  33 |   <Label key={value} bsStyle="primary" className="MultiSelectRenderer__tag">
> 34 |     {options.find(opt => opt[valueKey] === value)[labelKey]}
  35 |     <Button
  36 |       bsStyle="link"
  37 |       className="MultiSelectRenderer__remo
<img width="1115" alt="screen shot 2018-06-20 at 20 27 52" src="https://user-images.githubusercontent.com/40407762/41677299-308d8f40-74c8-11e8-89f1-d4a0cd68f509.png">
ve-tag-btn"
View compiled
render
src/ui/pages/common/MultiSelectRenderer.js:88
  85 |         </span>
  86 |       </InputGroup>
  87 |       <br />
> 88 |       { this.renderTags() }
  89 |     </div>
  90 |   );
  91 | }
View compiled
▼ 21 stack frames were expanded.
finishClassComponent
node_modules/react-dom/cjs/react-dom.development.js:7873
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js:10224
workLoop
node_modules/react-dom/cjs/react-dom.development.js:10288
callCallback
node_modules/react-dom/cjs/react-dom.development.js:542
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:581
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:438
renderRoot
node_modules/react-dom/cjs/react-dom.development.js:10366
performWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js:11014
performWork
node_modules/react-dom/cjs/react-dom.development.js:10967
requestWork
node_modules/react-dom/cjs/react-dom.development.js:10878
scheduleWorkImpl
node_modules/react-dom/cjs/react-dom.development.js:10732
enqueueSetState
node_modules/react-dom/cjs/react-dom.development.js:6212
setState
node_modules/react/cjs/react.development.js:242
onStateChange
node_modules/react-redux/es/components/connectAdvanced.js:205
notify
node_modules/react-redux/es/utils/Subscription.js:26
notifyNestedSubs
node_modules/react-redux/es/utils/Subscription.js:65
onStateChange
node_modules/react-redux/es/components/connectAdvanced.js:202
notify
node_modules/react-redux/es/utils/Subscription.js:26
notifyNestedSubs
node_modules/react-redux/es/utils/Subscription.js:65
onStateChange
node_modules/react-redux/es/components/connectAdvanced.js:202
dispatch
node_modules/redux/es/createStore.js:173
▲ 21 stack frames were expanded.
(anonymous function)
src/state/pages/actions.js:324
  321 | 
  322 | export const fetchPageForm = pageCode => dispatch => fetchPage(pageCode)(dispatch)
  323 |   .then((response) => {
> 324 |     dispatch(initialize('page', response.payload));
  325 |   })
  326 |   .catch(() => {});
  327 | 
View compiled

**Comment by nicpuddu** [comment]
hi @AngeloHulshout could you please specify which archetype you used when creating the app?

if possible specify the whole `mvn archetype:generate` command you used.

**Comment by AngeloHulshout** [comment]
Hi there,

I used wat was specified in the documentation:

mvn archetype:generate -Dfilter=entando-archetype-webapp-generic -DarchetypeCatalog=local

Angelo Hulshout
angelo@delphino-consultancy.nl

**Comment by AngeloHulshout** [comment]
@nicpuddu Any news on this? I haven't had time to rebuild and try again yet, but I can do that if it helps.

**Comment by nicpuddu** [comment]
@AngeloHulshout we are currently investigating the issue, we'll let you know as soon as we have some additional information

**Comment by nicpuddu** [comment]
@AngeloHulshout after several attempts we were not able to reproduce the reported error, could you please give us more details?

the given archetype does not come with a pre-existing contact page and we could not replicate the error on any of the other existing pages.
