### ISSUE TITLE
Page model not saved?

### ISSUE THREAD

**Issue by AngeloHulshout** [entando/app-builder#396]
I built the AppBuilder from source as instructed in the manuals (Welcome to Entando). After continuing, doing the tutorial for the Mortgage Application, the Page Model created in the first step of the tutorial is not saved. Is this because I missed a step somewhere (which makes this a documentation issue), or a bug?

1. I built as instructed in https://docs.entando.com/#_building_from_source
2. I disabled Mocks 

Please advice, if it's a documentation issue I'd be happy to fix it.

**Comment by kspokas** [comment]
Did you also provide the DOMAIN environment variable (along with USE_MOCKS=false) in the .env.development.local file in the root of the app-builder project?  It should point to the Entando Mapp Engine instance (e.g., DOMAIN=http://localhost:8180/entando-applicant).   If the domain value is missing or not a valid URL, it will revert to enabling mocks which might explain the values not updating.

**Comment by AngeloHulshout** [comment]
@kspokas Figured that out meanwhile. It's partly a documentation issue - for a new user it's not entirely clear in the docs that running hte MApp engine is required.

**Comment by AngeloHulshout** [comment]
Alas, nor with local build, nor with a remote MApp engine can I save the data.
I did notice that if I leave out the trailing '/' out of the DOMAIN, I can't login to the AppBuilder. With the trailin '/' I can, which seems to indicate that it connect properly.

**Comment by kspokas** [comment]
I was able to replicate this scenario and there is indeed a problem in the master branch of app-builder.  I was able to successfully connect using the "v5.0.0-release" branch of app-builder however.   I will add a step to checkout a release branch, and add a mention that the app-builder requires a running mapp engine instance so the work flow is more clear

**Comment by AngeloHulshout** [comment]
Great! I'll try that to see if everything works as it should then.

**Comment by AngeloHulshout** [comment]
@kspokas I see your changes in Github, but not on the docs.entando.com, missed a push?

**Comment by kspokas** [comment]
We had a couple commits clash, looks like this got all straightened out.

**Comment by AngeloHulshout** [comment]
Going to give it a quick try later this week, I've been otherwise occupied but picking up in August.

Angelo
-- 
Delphino Consultancy - software architecture, training and coaching
T 06 2531 9743  /  E angelo@delphino-consultancy.nl <mailto:angelo@delphino-consultancy.nl>
W http://www.delphino-consultancy.nl <http://www.delphino-consultancy.nl/>  / KVK Eindhoven 17228522 / GPG 487A55D0
