### ISSUE TITLE
Error in Data Types Page

### ISSUE THREAD

**Issue by vocafeuvre** [entando/app-builder#549]
Hi there,

I just cloned the App Builder repo (branch v5.1.0-release), and I didn't set the env file so all the configuration are default. I wanted to run the app using the mocks. I'm using Node v10.16.0 and NPM 6.9.0.

After that I started the app, and I navigated the Dashboard, Page Designer, and UX Patterns modules just fine. However, when I reached Data and clicked on Data Types,
![image](https://user-images.githubusercontent.com/22189353/60735502-367b6000-9f86-11e9-8726-fe7f081414b2.png)
I then encountered this error page
![image](https://user-images.githubusercontent.com/22189353/60736965-89a3e180-9f8b-11e9-977b-34565f387ab5.png)
I also encountered the error in the master branch.

Seeing this as a minor issue, I tracked it down and saw that the thunk (fetchDataTypes) responsible for fetching the data types and setting them passed the payload object to the action creator (setDataTypes). 
![image](https://user-images.githubusercontent.com/22189353/60737507-9fb2a180-9f8d-11e9-91f2-622f82213e56.png)
The action creator did not transform the passed argument and the dispatched action still contained the object. The reducer (toIdList) however, was expecting an array instead of an object, so it threw the error. I resolved it by passing the payload array nested in the payload object down to the action creator.

May I create a new pull request for this?

**Comment by gidesan** [comment]
Fixed by https://github.com/entando/app-builder/commit/38588a34b7546a7ce151f88738d8e16a48c68897.
