### ISSUE TITLE
what is this project and what is its use case?

### ISSUE THREAD

**Issue by pouyamiralayi** [entando/app-builder#594]
Hi! is there any doc talking about what actually is this project, and what is its use case?
i also cloned the project, issued  `npm install` & `npm start` on the project, my browser opened localhost:3000 but nothing was shown to me.
thanks!

**Comment by joewhite101** [comment]
Hi @pouyamiralayi 

The Entando app builder is the front end environment where you can assemble an Entando application from micro-frontends and Entando widgets. For it to work you'll need to setup a backend entando instance and deploy everything the Kubernetes.

You can find more about setting up a full Entando 6 instance here:
https://es-entando.github.io/

And more about Entando in general here:
http://docs.entando.com/

Out of curiosity what brought you to the app builder?

**Comment by pouyamiralayi** [comment]
hi @joewhite101 thanks for the answer! now i understand.

> Out of curiosity what brought you to the app builder?


i was looking for an app builder solution, but i had something like web flow in my mind! :) anyway i like this project because i have never seen an environment filing the gap between front-end and kube like this!
cheers!
